version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: main
    commit-message:
      prefix: 'chore(deps)'
    labels:
      - dependencies
    groups:
      production-deps:
        dependency-type: production
        update-types:
          - minor
          - patch
        patterns:
          - '*'
      dev-deps:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - '*'
    schedule:
      interval: 'daily'

  - package-ecosystem: github-actions
    directories:
      - /.github/workflows
    target-branch: main
    schedule:
      interval: monthly
    groups:
      github_actions:
        patterns:
          - '*'

  - package-ecosystem: 'docker'
    directory: '/.devcontainer'
    schedule:
      interval: 'weekly'
