on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches: [main]
name: 'Trigger Release'
permissions:
  contents: write
  id-token: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GH_REPO_WRITE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - uses: actions/checkout@v6
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.releases_created == 'true' }}
      - name: Setup
        uses: ./tooling/github/setup
        if: ${{ steps.release.outputs.releases_created == 'true' }}
      - name: 'Publish @homestuck/eslint-config'
        working-directory: packages/eslint
        run: pnpm publish --access public --no-git-checks
        if: ${{ steps.release.outputs['packages/eslint--release_created'] }}
      - name: 'Publish @homestuck/prettier-config'
        working-directory: packages/prettier
        run: pnpm publish --access public --no-git-checks
        if: ${{ steps.release.outputs['packages/prettier--release_created'] }}
      - name: 'Publish @homestuck/tsconfig'
        working-directory: packages/tsconfig
        run: pnpm publish --access public --no-git-checks
        if: ${{ steps.release.outputs['packages/tsconfig--release_created'] }}
